## Лабораторная работа №1

Группа: ДПИ23-1<br>
Студент: Тарасов С.В.

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [17]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [18]:
file_1 = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32', skiprows = 1, delimiter = ',')
print(file_1[:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [19]:
sliced = file_1[:, 1:]
print(np.min(sliced, axis = 0))
print(np.max(sliced, axis = 0))
print(np.mean(sliced, axis = 0))
print(np.median(sliced, axis = 0))

[0 1]
[2147483647         39]
[2.16010017e+04 9.05528000e+00]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [20]:
print(np.clip(file_1[:, 1], 0, np.quantile(file_1[:, 1], 0.75, method = 'higher')))

[60 25 10 ... 65  5 65]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [21]:
print(np.count_nonzero(file_1[:, 1] == 0))
np.place(file_1, file_1 == 0, 1)

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [22]:
#уникальные рецепты - это рецепты, у которых не повторяются минуты и количество ингредиентов
len(np.unique(sliced, axis = 0))

4183

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [23]:
print(np.unique(file_1[:, 2], axis=0))
print(np.unique(file_1[:, 2], axis=0).size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [24]:
file_2 = file_1[np.where(file_1[:, 2] <= 5)]
print(file_2)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [25]:
file_3 = file_1[:, 2] / file_1[:, 1]
print(file_3)
print(np.max(file_3))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [27]:
file_1_sort = file_1[file_1[:, 1].argsort()] #сортируем рецепты по времени
file_1_sort = np.flip(file_1_sort, 0)#переворачиваем массив, чтобы отсортировать по убыванию
average_value = file_1_sort[::-1][:100, :] #выборка из 100 рецептов
print(f'Среднее количество ингредиентов: {np.mean(average_value[:, 2], axis = 0)}')

Среднее количество ингредиентов: 7.81


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [28]:
a = np.arange(file_1.shape[0])#создаем массив по максимальному значению строк
np.random.shuffle(a)#выбор случайных значений из массива а
row_random = file_1[a[:10]]
print(row_random)

[[296278    320     20]
 [152698     75      8]
 [ 86297     95     13]
 [316153     35     11]
 [ 36975     45      6]
 [288288     24      6]
 [ 74430     80     10]
 [280692     25      8]
 [316389     20      4]
 [208772     55     14]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [30]:
b = file_1[np.where(file_1[:, 2] < np.mean(average_value[:, 2]))].size
c = file_1.size
print(b * 100 / c)

37.266


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [31]:
file_1 = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32', skiprows = 1, delimiter = ',')
f = file_1[np.where((file_1[:, 1] <= 20) & (file_1[:, 2] <= 5))]
f2 = file_1[np.where((file_1[:, 1] > 20) & (file_1[:, 2] > 5))]
file_4 = np.insert(f2, 3, 0, axis = 1)
file_3 = np.insert(f, 3, 1, axis = 1)
f3 = np.vstack([file_3,file_4])
print(f3)

[[446597     15      5      1]
 [204134      5      3      1]
 [ 25623      6      4      1]
 ...
 [287943     85     15      0]
 [498432     65     15      0]
 [ 81993    140     14      0]]


 13. Выведите процент "простых" рецептов в датасете

In [32]:
t = f3[np.where(f3[:, 3] == 1)].size
d = f3[np.where(f3[:, 3] == 0)].size
print(t * 100/ d)

14.552102376599635


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [33]:
file_1 = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32', skiprows = 1, delimiter = ',')

short = file_1[np.where(file_1[:, 1] <= 10)]#создание массива коротких рецептов
standart = file_1[np.where((file_1[:, 1] < 20) & (file_1[:, 1] > 10))]#создание массива стандартных рецептов
long = file_1[np.where(file_1[:, 1] >= 20)]#создание массива долгих рецептов

size_min = np.min(np.array([short.shape[0], long.shape[0], standart.shape[0]]))
total = np.array([short[0:size_min,:], long[0:size_min,:], standart[0:size_min,:]])
print(total.shape)

(3, 7783, 3)
